In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3, 4, 5)

In [3]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
a = a.reshape(6, 10)
a.shape

torch.Size([6, 10])

In [5]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(10, size=(10,)).int()
b.type()

'torch.IntTensor'

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a * b

tensor([[  0.3222,   4.0534,  -1.7277,  -1.1372,   0.0000,  -3.7040,   0.0000,
          11.4799,   0.4910,  -2.0251],
        [ -4.6046,   0.8926,   5.6881,  -3.2633,  -0.0000,  -1.9917,  -0.0000,
          -4.1723,  -0.4067, -10.5585],
        [ -3.8123,   5.8065,  -4.4775,   5.4771,  -0.0000,  -5.3240,  -0.0000,
           2.0889,  -2.6695,  -3.0888],
        [ -1.1439,   4.4772,  -2.2540,  -0.9392,   0.0000, -14.8670,  -0.0000,
           6.6293,  -1.4087,  -0.2417],
        [  0.3352,   9.4010,   4.4768,  -2.7824,  -0.0000,  -3.7146,  -0.0000,
          -1.8781,  -1.5909,   1.4817],
        [ 10.5658,   3.6661,  -0.3439,  -0.6585,  -0.0000,   9.2027,   0.0000,
          -7.3952,   0.3959,   2.1571]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
torch.matmul(a, a.T)

tensor([[ 8.6677, -2.0566, -0.8313,  1.0292, -0.5115, -0.3092],
        [-2.0566,  8.7822,  0.5142,  0.6479,  2.5366, -0.7630],
        [-0.8313,  0.5142,  9.4105,  4.2740,  1.7056, -2.3939],
        [ 1.0292,  0.6479,  4.2740,  9.3546,  3.6877, -7.2594],
        [-0.5115,  2.5366,  1.7056,  3.6877,  6.5013,  0.6235],
        [-0.3092, -0.7630, -2.3939, -7.2594,  0.6235, 11.7532]])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1]).float()
x.requires_grad = True
z = torch.tensor([.5]).float()
z.requires_grad = True
t = torch.tensor([2]).float()
t.requires_grad = True
y = x**3 + z - 75*t
y.backward()
print(x.grad, z.grad, t.grad)

tensor([3.]) tensor([1.]) tensor([-75.])


In [9]:
# 8. Создайте единичный тензор размера 5x6
c = torch.ones((5, 6))
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
# 9. Переведите его в формат numpy
d = c.numpy()
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)